### ISSUE TITLE
Add the possibility to show add/overview menu link per entity type/bundle

### ISSUE THREAD

**Issue by DieterHolvoet** [wieni/wienimal_editor_toolbar#7]
## Summary

Add the possibility to show add/overview menu link per entity type/bundle.

### Basic example

Instead of this existing config:
```yaml
show_combined_content_overview: true
show_combined_add_content: true
content:
  node: all
```

it could look like this:
```yaml
content_add:
  node: all
content_overview:
  node: all
```
